-- Flujo separado para solicitar alta de alimentos canonicos del catalogo.

CREATE TABLE IF NOT EXISTS "public"."solicitudes_alta_alimentos" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "solicitante_id" uuid NOT NULL REFERENCES "public"."usuarios"("id"),
  "nombre" text NOT NULL,
  "categoria" text NOT NULL,
  "comentario_donante" text NULL,
  "estado" text NOT NULL DEFAULT 'pendiente',
  "comentario_admin" text NULL,
  "alimento_creado_id" bigint NULL REFERENCES "public"."alimentos"("id"),
  "revisado_por" uuid NULL REFERENCES "public"."usuarios"("id"),
  "fecha_revision" timestamptz NULL,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  CONSTRAINT "solicitudes_alta_alimentos_estado_check"
    CHECK ("estado" = ANY (ARRAY['pendiente'::text, 'aprobada'::text, 'rechazada'::text])),
  CONSTRAINT "solicitudes_alta_alimentos_nombre_check"
    CHECK (length(trim("nombre")) > 0),
  CONSTRAINT "solicitudes_alta_alimentos_categoria_check"
    CHECK (length(trim("categoria")) > 0)
);

CREATE TABLE IF NOT EXISTS "public"."solicitudes_alta_alimentos_unidades" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "solicitud_id" uuid NOT NULL REFERENCES "public"."solicitudes_alta_alimentos"("id") ON DELETE CASCADE,
  "unidad_id" bigint NOT NULL REFERENCES "public"."unidades"("id"),
  "es_unidad_principal" boolean DEFAULT false,
  CONSTRAINT "solicitudes_alta_alimentos_unidades_unique" UNIQUE ("solicitud_id", "unidad_id")
);

CREATE INDEX IF NOT EXISTS "idx_solicitudes_alta_alimentos_solicitante"
  ON "public"."solicitudes_alta_alimentos" ("solicitante_id");

CREATE INDEX IF NOT EXISTS "idx_solicitudes_alta_alimentos_estado"
  ON "public"."solicitudes_alta_alimentos" ("estado", "created_at" DESC);

CREATE INDEX IF NOT EXISTS "idx_solicitudes_alta_alimentos_unidades_solicitud"
  ON "public"."solicitudes_alta_alimentos_unidades" ("solicitud_id");

DROP TRIGGER IF EXISTS "trigger_solicitudes_alta_alimentos_updated_at"
  ON "public"."solicitudes_alta_alimentos";

CREATE TRIGGER "trigger_solicitudes_alta_alimentos_updated_at"
  BEFORE UPDATE ON "public"."solicitudes_alta_alimentos"
  FOR EACH ROW
  EXECUTE FUNCTION "public"."update_updated_at_column"();

ALTER TABLE "public"."solicitudes_alta_alimentos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."solicitudes_alta_alimentos_unidades" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "solicitudes_alta_select_own"
  ON "public"."solicitudes_alta_alimentos"
  FOR SELECT TO "authenticated"
  USING (
    "solicitante_id" = auth.uid()
    AND EXISTS (
      SELECT 1 FROM "public"."usuarios"
      WHERE "usuarios"."id" = auth.uid()
        AND "usuarios"."rol" = 'DONANTE'
        AND "usuarios"."estado" = 'activo'
    )
  );

CREATE POLICY "solicitudes_alta_select_admin"
  ON "public"."solicitudes_alta_alimentos"
  FOR SELECT TO "authenticated"
  USING (
    EXISTS (
      SELECT 1 FROM "public"."usuarios"
      WHERE "usuarios"."id" = auth.uid()
        AND "usuarios"."rol" = 'ADMINISTRADOR'
        AND "usuarios"."estado" = 'activo'
    )
  );

CREATE POLICY "solicitudes_alta_insert_donante"
  ON "public"."solicitudes_alta_alimentos"
  FOR INSERT TO "authenticated"
  WITH CHECK (
    "solicitante_id" = auth.uid()
    AND "estado" = 'pendiente'
    AND "comentario_admin" IS NULL
    AND "alimento_creado_id" IS NULL
    AND "revisado_por" IS NULL
    AND "fecha_revision" IS NULL
    AND EXISTS (
      SELECT 1 FROM "public"."usuarios"
      WHERE "usuarios"."id" = auth.uid()
        AND "usuarios"."rol" = 'DONANTE'
        AND "usuarios"."estado" = 'activo'
    )
  );

CREATE POLICY "solicitudes_alta_update_admin"
  ON "public"."solicitudes_alta_alimentos"
  FOR UPDATE TO "authenticated"
  USING (
    EXISTS (
      SELECT 1 FROM "public"."usuarios"
      WHERE "usuarios"."id" = auth.uid()
        AND "usuarios"."rol" = 'ADMINISTRADOR'
        AND "usuarios"."estado" = 'activo'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM "public"."usuarios"
      WHERE "usuarios"."id" = auth.uid()
        AND "usuarios"."rol" = 'ADMINISTRADOR'
        AND "usuarios"."estado" = 'activo'
    )
  );

CREATE POLICY "solicitudes_alta_unidades_select_visible"
  ON "public"."solicitudes_alta_alimentos_unidades"
  FOR SELECT TO "authenticated"
  USING (
    EXISTS (
      SELECT 1
      FROM "public"."solicitudes_alta_alimentos" saa
      WHERE saa."id" = "solicitudes_alta_alimentos_unidades"."solicitud_id"
        AND (
          (
            saa."solicitante_id" = auth.uid()
            AND EXISTS (
              SELECT 1 FROM "public"."usuarios"
              WHERE "usuarios"."id" = auth.uid()
                AND "usuarios"."rol" = 'DONANTE'
                AND "usuarios"."estado" = 'activo'
            )
          )
          OR EXISTS (
            SELECT 1 FROM "public"."usuarios"
            WHERE "usuarios"."id" = auth.uid()
              AND "usuarios"."rol" = 'ADMINISTRADOR'
              AND "usuarios"."estado" = 'activo'
          )
        )
    )
  );

CREATE POLICY "solicitudes_alta_unidades_insert_owner_pending_or_admin"
  ON "public"."solicitudes_alta_alimentos_unidades"
  FOR INSERT TO "authenticated"
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM "public"."solicitudes_alta_alimentos" saa
      WHERE saa."id" = "solicitudes_alta_alimentos_unidades"."solicitud_id"
        AND (
          (
            saa."solicitante_id" = auth.uid()
            AND saa."estado" = 'pendiente'
            AND EXISTS (
              SELECT 1 FROM "public"."usuarios"
              WHERE "usuarios"."id" = auth.uid()
                AND "usuarios"."rol" = 'DONANTE'
                AND "usuarios"."estado" = 'activo'
            )
          )
          OR EXISTS (
            SELECT 1 FROM "public"."usuarios"
            WHERE "usuarios"."id" = auth.uid()
              AND "usuarios"."rol" = 'ADMINISTRADOR'
              AND "usuarios"."estado" = 'activo'
          )
        )
    )
  );

CREATE POLICY "solicitudes_alta_unidades_update_admin"
  ON "public"."solicitudes_alta_alimentos_unidades"
  FOR UPDATE TO "authenticated"
  USING (
    EXISTS (
      SELECT 1 FROM "public"."usuarios"
      WHERE "usuarios"."id" = auth.uid()
        AND "usuarios"."rol" = 'ADMINISTRADOR'
        AND "usuarios"."estado" = 'activo'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM "public"."usuarios"
      WHERE "usuarios"."id" = auth.uid()
        AND "usuarios"."rol" = 'ADMINISTRADOR'
        AND "usuarios"."estado" = 'activo'
    )
  );

CREATE POLICY "solicitudes_alta_unidades_delete_admin"
  ON "public"."solicitudes_alta_alimentos_unidades"
  FOR DELETE TO "authenticated"
  USING (
    EXISTS (
      SELECT 1 FROM "public"."usuarios"
      WHERE "usuarios"."id" = auth.uid()
        AND "usuarios"."rol" = 'ADMINISTRADOR'
        AND "usuarios"."estado" = 'activo'
    )
  );

CREATE OR REPLACE FUNCTION "public"."aprobar_solicitud_alta_alimento"(
  "p_solicitud_id" uuid,
  "p_nombre" text,
  "p_categoria" text,
  "p_unidad_ids" bigint[],
  "p_unidad_principal_id" bigint
) RETURNS bigint
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path = ''
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_alimento_id bigint;
  v_unidad_id bigint;
  v_unidad_ids bigint[];
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM public.usuarios
    WHERE id = v_user_id
      AND rol = 'ADMINISTRADOR'
      AND estado = 'activo'
  ) THEN
    RAISE EXCEPTION 'Solo un administrador activo puede aprobar solicitudes de alta de alimento';
  END IF;

  IF p_nombre IS NULL OR length(trim(p_nombre)) = 0 THEN
    RAISE EXCEPTION 'El nombre del alimento es obligatorio';
  END IF;

  IF p_categoria IS NULL OR length(trim(p_categoria)) = 0 THEN
    RAISE EXCEPTION 'La categoria del alimento es obligatoria';
  END IF;

  SELECT array_agg(DISTINCT unidad_id)
  INTO v_unidad_ids
  FROM unnest(p_unidad_ids) AS unidad_ids(unidad_id)
  WHERE unidad_id IS NOT NULL;

  IF v_unidad_ids IS NULL OR array_length(v_unidad_ids, 1) = 0 THEN
    RAISE EXCEPTION 'Debes seleccionar al menos una unidad de medida';
  END IF;

  IF p_unidad_principal_id IS NOT NULL AND NOT (p_unidad_principal_id = ANY(v_unidad_ids)) THEN
    RAISE EXCEPTION 'La unidad principal debe estar entre las unidades seleccionadas';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.solicitudes_alta_alimentos
    WHERE id = p_solicitud_id
      AND estado <> 'pendiente'
  ) THEN
    RAISE EXCEPTION 'La solicitud ya fue revisada';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.solicitudes_alta_alimentos
    WHERE id = p_solicitud_id
      AND estado = 'pendiente'
  ) THEN
    RAISE EXCEPTION 'Solicitud de alta no encontrada';
  END IF;

  INSERT INTO public.alimentos (nombre, categoria)
  VALUES (trim(p_nombre), trim(p_categoria))
  RETURNING id INTO v_alimento_id;

  FOREACH v_unidad_id IN ARRAY v_unidad_ids LOOP
    INSERT INTO public.alimentos_unidades (
      alimento_id,
      unidad_id,
      es_unidad_principal
    )
    VALUES (
      v_alimento_id,
      v_unidad_id,
      v_unidad_id = p_unidad_principal_id
    );
  END LOOP;

  UPDATE public.solicitudes_alta_alimentos
  SET estado = 'aprobada',
      alimento_creado_id = v_alimento_id,
      revisado_por = v_user_id,
      fecha_revision = now(),
      updated_at = now()
  WHERE id = p_solicitud_id;

  RETURN v_alimento_id;
END;
$$;

REVOKE ALL ON FUNCTION "public"."aprobar_solicitud_alta_alimento"(uuid, text, text, bigint[], bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION "public"."aprobar_solicitud_alta_alimento"(uuid, text, text, bigint[], bigint) FROM anon;
GRANT EXECUTE ON FUNCTION "public"."aprobar_solicitud_alta_alimento"(uuid, text, text, bigint[], bigint) TO authenticated;

REVOKE ALL ON TABLE "public"."solicitudes_alta_alimentos" FROM anon;
REVOKE ALL ON TABLE "public"."solicitudes_alta_alimentos" FROM authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE "public"."solicitudes_alta_alimentos" TO authenticated;
GRANT ALL ON TABLE "public"."solicitudes_alta_alimentos" TO service_role;
REVOKE ALL ON TABLE "public"."solicitudes_alta_alimentos_unidades" FROM anon;
REVOKE ALL ON TABLE "public"."solicitudes_alta_alimentos_unidades" FROM authenticated;
GRANT SELECT, INSERT ON TABLE "public"."solicitudes_alta_alimentos_unidades" TO authenticated;
GRANT ALL ON TABLE "public"."solicitudes_alta_alimentos_unidades" TO service_role;
REVOKE ALL ON SEQUENCE "public"."solicitudes_alta_alimentos_unidades_id_seq" FROM anon;
REVOKE ALL ON SEQUENCE "public"."solicitudes_alta_alimentos_unidades_id_seq" FROM authenticated;
GRANT USAGE, SELECT ON SEQUENCE "public"."solicitudes_alta_alimentos_unidades_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE "public"."solicitudes_alta_alimentos_unidades_id_seq" TO service_role;

CREATE OR REPLACE FUNCTION "public"."validar_donacion_alimento_canonico"()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  IF NEW.alimento_id IS NULL THEN
    RAISE EXCEPTION 'Las nuevas donaciones deben referenciar un alimento existente';
  END IF;

  IF COALESCE(NEW.es_producto_personalizado, false) THEN
    RAISE EXCEPTION 'Las nuevas donaciones no pueden usar producto personalizado';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "trigger_validar_donacion_alimento_canonico"
  ON "public"."donaciones";

CREATE TRIGGER "trigger_validar_donacion_alimento_canonico"
  BEFORE INSERT ON "public"."donaciones"
  FOR EACH ROW
  EXECUTE FUNCTION "public"."validar_donacion_alimento_canonico"();
