BEGIN;

-- Las donaciones canceladas se conservan para mantener el historial operativo.
-- Los campos de cancelación ya forman parte del esquema inicial; esta migración
-- refuerza sus reglas y reemplaza la eliminación física por una transición de estado.

DROP POLICY IF EXISTS "Donantes pueden eliminar sus propias donaciones pendientes" ON public.donaciones;
DROP POLICY IF EXISTS admin_delete_donaciones ON public.donaciones;
DROP POLICY IF EXISTS donaciones_delete_allowed ON public.donaciones;
REVOKE DELETE ON TABLE public.donaciones FROM anon, authenticated;

DROP POLICY IF EXISTS "Donantes pueden actualizar sus propias donaciones pendientes" ON public.donaciones;
DROP POLICY IF EXISTS admin_update_donaciones ON public.donaciones;
DROP POLICY IF EXISTS operador_update_donaciones ON public.donaciones;
DROP POLICY IF EXISTS donaciones_update_allowed ON public.donaciones;

CREATE POLICY donaciones_update_allowed
  ON public.donaciones
  FOR UPDATE
  TO authenticated
  USING (
    (
      user_id = (SELECT auth.uid())
      AND estado = 'Pendiente'::text
      AND (SELECT private_auth.current_user_role()) = 'DONANTE'::text
      AND (SELECT private_auth.current_user_estado()) = 'activo'::text
    )
    OR (
      (SELECT private_auth.current_user_role()) = ANY (ARRAY['ADMINISTRADOR'::text, 'OPERADOR'::text])
      AND (SELECT private_auth.current_user_estado()) = 'activo'::text
    )
  )
  WITH CHECK (
    (
      user_id = (SELECT auth.uid())
      AND estado = ANY (ARRAY['Pendiente'::text, 'Cancelada'::text])
      AND (SELECT private_auth.current_user_role()) = 'DONANTE'::text
      AND (SELECT private_auth.current_user_estado()) = 'activo'::text
    )
    OR (
      (SELECT private_auth.current_user_role()) = 'ADMINISTRADOR'::text
      AND (SELECT private_auth.current_user_estado()) = 'activo'::text
    )
    OR (
      (SELECT private_auth.current_user_role()) = 'OPERADOR'::text
      AND estado <> 'Cancelada'::text
      AND (SELECT private_auth.current_user_estado()) = 'activo'::text
    )
  );

CREATE TABLE IF NOT EXISTS public.auditoria_donaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  donacion_id integer NOT NULL REFERENCES public.donaciones(id) ON DELETE RESTRICT,
  accion text NOT NULL,
  estado_anterior text NOT NULL,
  estado_nuevo text NOT NULL,
  usuario_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  rol_usuario text NOT NULL,
  motivo text NOT NULL,
  observaciones text,
  fecha_evento timestamp with time zone NOT NULL DEFAULT now(),
  metadatos jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT auditoria_donaciones_accion_check
    CHECK (accion = 'cancelacion'::text),
  CONSTRAINT auditoria_donaciones_estado_anterior_check
    CHECK (estado_anterior = 'Pendiente'::text),
  CONSTRAINT auditoria_donaciones_estado_nuevo_check
    CHECK (estado_nuevo = 'Cancelada'::text),
  CONSTRAINT auditoria_donaciones_motivo_check
    CHECK (motivo = ANY (ARRAY[
      'error_donante'::text,
      'no_disponible'::text,
      'calidad_inadecuada'::text,
      'logistica_imposible'::text,
      'duplicado'::text,
      'solicitud_donante'::text,
      'otro'::text
    ])),
  CONSTRAINT auditoria_donaciones_unique_action
    UNIQUE (donacion_id, accion)
);

CREATE INDEX IF NOT EXISTS idx_auditoria_donaciones_donacion_fecha
  ON public.auditoria_donaciones (donacion_id, fecha_evento DESC);

CREATE INDEX IF NOT EXISTS idx_auditoria_donaciones_usuario_fecha
  ON public.auditoria_donaciones (usuario_id, fecha_evento DESC);

ALTER TABLE public.auditoria_donaciones ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.auditoria_donaciones FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.auditoria_donaciones TO authenticated;
GRANT ALL ON TABLE public.auditoria_donaciones TO service_role;

DROP POLICY IF EXISTS auditoria_donaciones_select_visible ON public.auditoria_donaciones;
CREATE POLICY auditoria_donaciones_select_visible
  ON public.auditoria_donaciones
  FOR SELECT
  TO authenticated
  USING (
    (
      (SELECT private_auth.current_user_role()) = ANY (ARRAY['ADMINISTRADOR'::text, 'OPERADOR'::text])
      AND (SELECT private_auth.current_user_estado()) = 'activo'::text
    )
    OR EXISTS (
      SELECT 1
      FROM public.donaciones d
      WHERE d.id = auditoria_donaciones.donacion_id
        AND d.user_id = (SELECT auth.uid())
        AND (SELECT private_auth.current_user_role()) = 'DONANTE'::text
        AND (SELECT private_auth.current_user_estado()) = 'activo'::text
    )
  );

-- Ningún cliente recibe políticas de INSERT, UPDATE o DELETE para la bitácora.
-- El único INSERT ocurre desde el trigger SECURITY DEFINER de abajo.

CREATE OR REPLACE FUNCTION public.validar_cancelacion_donacion()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_actor_id uuid := (SELECT auth.uid());
  v_actor_role text;
BEGIN
  IF OLD.estado = 'Cancelada'::text THEN
    RAISE EXCEPTION 'Una donacion cancelada no puede modificarse ni cancelarse nuevamente';
  END IF;

  IF NEW.estado = 'Cancelada'::text THEN
    IF OLD.estado <> 'Pendiente'::text THEN
      RAISE EXCEPTION 'Solo se pueden cancelar donaciones pendientes';
    END IF;

    IF v_actor_id IS NULL THEN
      RAISE EXCEPTION 'Se requiere un usuario autenticado para cancelar una donacion';
    END IF;

    SELECT u.rol
    INTO v_actor_role
    FROM public.usuarios u
    WHERE u.id = v_actor_id
      AND u.estado = 'activo'::text;

    IF v_actor_role IS NULL OR v_actor_role NOT IN ('DONANTE'::text, 'ADMINISTRADOR'::text) THEN
      RAISE EXCEPTION 'Solo un donante o administrador activo puede cancelar una donacion';
    END IF;

    IF v_actor_role = 'DONANTE'::text AND NEW.user_id IS DISTINCT FROM v_actor_id THEN
      RAISE EXCEPTION 'Un donante solo puede cancelar sus propias donaciones';
    END IF;

    IF v_actor_role = 'DONANTE'::text AND NEW.motivo_cancelacion <> 'solicitud_donante'::text THEN
      RAISE EXCEPTION 'Las cancelaciones realizadas por un donante deben usar el motivo solicitud_donante';
    END IF;

    IF NEW.motivo_cancelacion IS NULL THEN
      RAISE EXCEPTION 'El motivo de cancelacion es obligatorio';
    END IF;

    NEW.usuario_cancelacion_id := v_actor_id;
    NEW.fecha_cancelacion := now();
    NEW.actualizado_en := now();
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trigger_validar_cancelacion_donacion
BEFORE UPDATE ON public.donaciones
FOR EACH ROW
EXECUTE FUNCTION public.validar_cancelacion_donacion();

CREATE OR REPLACE FUNCTION public.registrar_auditoria_cancelacion_donacion()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_actor_role text;
BEGIN
  IF OLD.estado = 'Pendiente'::text AND NEW.estado = 'Cancelada'::text THEN
    SELECT u.rol
    INTO v_actor_role
    FROM public.usuarios u
    WHERE u.id = NEW.usuario_cancelacion_id;

    INSERT INTO public.auditoria_donaciones (
      donacion_id,
      accion,
      estado_anterior,
      estado_nuevo,
      usuario_id,
      rol_usuario,
      motivo,
      observaciones,
      fecha_evento,
      metadatos
    )
    VALUES (
      NEW.id,
      'cancelacion'::text,
      OLD.estado,
      NEW.estado,
      NEW.usuario_cancelacion_id,
      COALESCE(v_actor_role, 'DESCONOCIDO'::text),
      NEW.motivo_cancelacion,
      NEW.observaciones_cancelacion,
      COALESCE(NEW.fecha_cancelacion, now()),
      jsonb_build_object('origen', 'trigger_validar_cancelacion_donacion')
    );
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trigger_auditoria_cancelacion_donacion
AFTER UPDATE OF estado ON public.donaciones
FOR EACH ROW
EXECUTE FUNCTION public.registrar_auditoria_cancelacion_donacion();

CREATE OR REPLACE FUNCTION public.bloquear_mutacion_auditoria_donaciones()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'La bitacora de auditoria de donaciones es inmutable';
END;
$$;

CREATE OR REPLACE TRIGGER trigger_inmutabilidad_auditoria_donaciones
BEFORE UPDATE OR DELETE ON public.auditoria_donaciones
FOR EACH ROW
EXECUTE FUNCTION public.bloquear_mutacion_auditoria_donaciones();

REVOKE ALL ON FUNCTION public.validar_cancelacion_donacion() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.registrar_auditoria_cancelacion_donacion() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.bloquear_mutacion_auditoria_donaciones() FROM PUBLIC, anon, authenticated;

COMMENT ON TABLE public.auditoria_donaciones IS
  'Bitacora inmutable de transiciones de cancelacion de donaciones.';

COMMIT;
